public class qcaArray {
	
	public static String[] questions = //list of questions
	{
		"Which does not belong in the primary sector?",
		"Which is not a function of business?",
		"As developing economies become developed, there is a change in employment and output from",
		"Which is not usually part of the tertiary sector?",
		"Increasing the worth of resources during the production of goods and services is known as",
		"Utilities, such as electricity and water, are considered part of the tertiary sector because",
		"‘Product’ refers to",
		"An entrepreneur",
		"Specialization has many advantages but does not",
		"Production is",
		"Resources used in the production process are",
		"In production, the difference between the costs of inputs and the price received for outputs is",
		"Delivery vans are an example of which type of factor input",
		"An advantage of specialization does not include",
		"In an economy, the primary sector consists of",
		"Organizations operating in the secondary sector",
		"An unlikely opportunity cost of investing $50,000 in new product development is",
		"Which types of businesses do not operate in the tertiary sector?",
		"Which is not a factor of production?",
		"Which is the least specialized?",
		"Which is not classified as land when referring to factors of production?",
		"Which of the following is likely to have the largest division of labour?",
		"Which of the following is not a sector of the economy a business will be operating in?",
		"Which of the following is not part of the quaternary sector?",
		"Percentage increase in total industry sales revenue.",
		"The firm that has the largest market share in an industry (value or volume).",
		"Marketing that takes account of the moral issues involved in business is known as",
		"Which of the following would not be a characteristic of a particular market?",
		"Which of the following is not a method to measure the size of a market?",
		"The marketing of a new product will impact which other business functions?",
		"The total level of sales of producers within a market is termed:",
		"The percentage of sales in the total market sold by one organization is termed:",
		"A key point of difference in the marketing of goods and services is that services are:",
		"Which of the following things is marketing not concerned with?",
		"Which is a different marketing approach to market orientation that could be used?",
		"Which of the following is least likely to be an objective of social marketing of a non-profit organization?",
		"For-profit businesses are least likely to have which of the following marketing objectives?",
		"Which cannot be applied to firms with a market orientation?",
		"Which of the following would not be a characteristic of a particular market?",
		"A ‘DINKY’ – double income, no kids yet is market segmentation based on:",
		"Having a specific market mix for a distinctive section of a particular market is:",
		"Demographic differences that can be used as a basis for market segmentation does not include:",
		"The placing of a brand or product within a positioning map is decided by:",
		"A marketing plan is NOT likely to include:",
		"If Mercedes is perceived as being inferior to rivals BMW, Lexis and Audi, the firm should renew its:",
		"Any medium-to long-term plan for achieving the marketing objectives of a business:",
		"The process of marketing planning is least likely to include:",
		"An advantage of mass marketing would least likely include:",
		"Which of the following would not be used in demographic segmentation of a particular market?",
		"Which of the following is least likely to be an advantage of niche marketing?",
		"Identifying different segments within a market and targeting different products to them",
		"Which basis for segmentation is least likely to be considered by a private school?",
		"Markets are segmented in a number of ways, but not using:"
	};
	
	public static String[][] choices = //list of mulitple choices
	{
		{"Agriculture", "Oil Extraction", "Forestry", "Teaching"},
		{"Finance", "Entrepreneurship", "Human resources management", "Operations management"},
		{"Primary to tertiary", "Secondary to tertiary", "Tertiary to secondary", "Primary to secondary"},
		{"Engineering", "Tourism", "Retail", "Banking"},
		{"Value function", "Adding Value", "Production function", "Production"},
		{"These are services being provided", "These are extracted and not manufactured", "They're required in the production of goods and services", "The government owns them"},
		{"Only manufactured goods", "Only services", "Only goods", "Goods and services"},
		{"Is the main shareholder", "Takes risks and organizes the other 3 factors of production", "Manages production", "Is a sole trader or the main shareholder in a business"},
		{"Develop workers’ skills or expertise", "Improve efficiency in a business’s operations", "Provide greater customer choice", "Increase output"},
		{"Any physical output that has value added", "The final stage of the manufacturing process", "Using factors of production to make goods and services", "Manufacturing goods and services in the secondary sector"},
		{"Human capital resources", "Working capital", "Factors of production", "Primary resources"},
		{"Sales revenue", "Profit or loss", "Added value", "Income"},
		{"Capital", "Labour", "Finance", "Machinery"},
		{"Being more competitive", "Increases in productivity", "Being able to mass produce products", "The monotony of doing the same job"},
		{"Businesses requiring additional finance", "New start-up enterprises", "Fishing, farming and extracting minerals", "Government utilities such as water and gas"},
		{"Manufacture goods", "Provide both goods and services", "Have the largest employment sector in developed countries", "Are labour intensive"},
		{"Purchasing a luxury company car for the CEO", "Not spending $50,000 on the promotion of an existing product", "Not hiring an extra salesperson for a year", "Securing a $50,000 loan from a bank"},
		{"Hotels", "Insurance", "Clothing and textiles", "Security and protection"},
		{"Human resources", "Land", "Entrepreneurship", "Capital"},
		{"Labourer", "Bus driver", "Professional hockey player", "Intellectual property lawyer"},
		{"Gas", "Paper", "Forestry", "Corn"},
		{"Beautician", "Tailor", "University lecturer", "Artisan furniture maker"},
		{"Agrarian sector", "Secondary sector", "Primary sector", "Quaternary sector"},
		{"Transportation and distribution", "Research and development", "Information and communication technology", "Consultancy services"},
		{"Market size", "Market share", "Market growth", "Market demographics"},
		{"Has a monopoly in that market", "Has the first mover advantage", "Is the market front runner", "Is the market leader"},
		{"Ethical marketing", "Social network marketing", "Environmental marketing", "Public relations management"},
		{"Market size", "Barriers to entry", "Customer base", "Market share"},
		{"Value of products sold (revenue)", "Number of customers", "Number of overseas markets", "Volume of sales (units sold)"},
		{"Operations management", "Human resources", "Finance", "All three departments above"},
		{"The market",	"Market growth", "Market size", "Market share"},
		{"Market size", "Market share", "Market growth", "The market"},
		{"Immediately accessible on purchase", "Intangible", "Undifferentiated", "Perishable"},
		{"Understanding the needs and wants of customers", "Recruiting and training the best sales team", "Customer relationship management", "Meeting the needs and wants of customers"},
		{"Product orientation", "Service orientation", "Consumer orientation","E-commerce orientation"},
		{"To improve brand recognition","To develop new products","To generate and raise awareness of a cause","To increase membership support"},
		{"Increased sales revenue", "Increased number of customer complaints", "Better product and brand awareness", "Increased market share"},
		{"Market research discovers the needs and wants of customers", "The customer’s ability and willingness to pay determines prices", "A firm design and makes products they think will sell best", "Distribution makes it convenient to purchase and receive the product"},
		{"Market growth rate", "Demographic characteristics", "Geographic characteristics", "Market share"},
		{"Demographic factors", "Psychographic factors", "Geographic factors", "Infographic factors"},
		{"Market segmentation", "Targeting", "Psychographic profiling", "Consumer profiling"},
		{"Family size", "Lifestyle", "Religion", "Gender"},
		{"Consumers", "Competitors", "Focus groups", "Producers"},
		{"A SWOT analysis", "A marketing budget", "SMART marketing objectives", "Specific marketing actions"},
		{"Corporate image", "Positioning", "Premium pricing", "Segmentation"},
		{"Corporate plan", "Marketing plan", "Integrated marketing mix", "Strategic plan"},
		{"Meeting marketing objectives", "Preparing sales forecasts", "Marketing promotion", "Developing marketing strategies"},
		{"Establishing a large customer base", "Charging higher prices for products", "Achieving economies of scale", "Average cost per potential customer is reduced"},
		{"Language", "Location", "Age", "Gender"},
		{"Charging higher prices for products", "More effective marketing focus", "Average cost per potential customer is reduced", "Personalized customer service"},
		{"Market segment", "Consumer profiling", "Market segmentation", "Target market"},
		{"Geographical location", "Age", "Religion", "Socio-economic grouping"},
		{"Demographic differences", "Psychographic differences", "Infographic differences", "Geographic differences"}
	};
	
	public static char[] answers = //list of answers
	{
		'D',
		'B',
		'B',
		'A',
		'B',
		'A',
		'D',
		'B',
		'C',
		'C',
		'C',
		'C',
		'A',
		'D',
		'C',
		'A',
		'A',
		'C',
		'A',
		'A',
		'B',
		'C',
		'A',
		'A',
		'C',
		'D',
		'A',
		'D',
		'C',
		'D',
		'C',
		'B',
		'B',
		'B',
		'A',
		'B',
		'B',
		'C',
		'D',
		'A',
		'B',
		'B',
		'A',
		'A',
		'B',
		'B',
		'C',
		'B',
		'B',
		'C',
		'C',
		'C',
		'C'
	};

}